version: "3"

networks:
  managy:

services:
  # nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - managy

  # php
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-app
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - managy

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patient_management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - managy
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - managy

volumes:
  db_data:  